SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS call_recordings;
DROP TABLE IF EXISTS workflow_runs;
DROP TABLE IF EXISTS investigations;
DROP TABLE IF EXISTS report_fields;
DROP TABLE IF EXISTS report_sections;
DROP TABLE IF EXISTS inspection_reports;
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS calendar_events;
DROP TABLE IF EXISTS inspection_request_status_history;
DROP TABLE IF EXISTS inspection_requests;
DROP TABLE IF EXISTS insurer_clients;
DROP TABLE IF EXISTS client_addresses;
DROP TABLE IF EXISTS clients;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS alara_offices;
DROP TABLE IF EXISTS insurers;
SET FOREIGN_KEY_CHECKS = 1;
