-- Obsoleto para ejecución manual parcial: puede dejar la BD a medias y seguir
-- fallando Prisma (ej. falta clients.address_line tras añadir solo amount_in_force).
--
-- Usar en su lugar (idempotente, todas las columnas habituales):
--   alara_sync_prisma_columns_mysql.sql
--
-- Si tu hosting no permite procedimientos almacenados, abre ese archivo y ejecuta
-- solo los bloques ALTER que necesites, o usa README-MYSQL-MANUAL.md.
