import type { ReportSectionDef } from './fieldTypes';
import {
  AFFIRMATIVE_YES_KEYS_ALCOHOL_DROGAS,
  AFFIRMATIVE_YES_KEYS_DEPORTES_RIESGO,
  AFFIRMATIVE_YES_KEYS_JUICIOS,
  AFFIRMATIVE_YES_KEYS_RIESGOS_LABORALES,
  AFFIRMATIVE_YES_KEYS_SALUD,
  AFFIRMATIVE_YES_KEYS_SEGURIDAD,
  visibleWhenAnySi,
} from './fieldTypes';

/** Plantilla por defecto (alineada con seed INSPECTION_REPORT_V1). */
export const defaultReportSections = (): ReportSectionDef[] => [
  {
    code: 'DATOS_PERSONALES',
    title: 'Datos personales',
    fields: [
      { key: 'first_name', label: 'Nombres' },
      { key: 'last_name', label: 'Apellidos' },
      { key: 'id_type', label: 'Tipo de documento', type: 'select' },
      { key: 'id_number', label: 'Número de documento' },
      { key: 'home_address', label: 'Domicilio Particular' },
      { key: 'residence_time', label: 'Tiempo de Residencia' },
      { key: 'foreign_residence', label: 'Residencia en el extranjero (Dónde / cuándo)', type: 'textarea' },
      { key: 'mobile', label: 'Celular' },
      { key: 'email', label: 'E-mail' },
      { key: 'dob', label: 'Fecha de Nacimiento', type: 'date' },
      { key: 'nationality', label: 'Nacionalidad' },
      { key: 'marital_status', label: 'Estado Civil', type: 'select' },
      {
        key: 'spouse_name',
        label: 'Nombre del Cónyuge',
        visibleWhen: { key: 'marital_status', values: ['Casado', 'Unido'] },
      },
      { key: 'children', label: 'Hijos' },
    ],
  },
  {
    code: 'PROFESION_LABORAL',
    title: 'Profesión – Actividad Laboral',
    fields: [
      { key: 'profession_studies', label: 'Profesión / Estudios Cursados' },
      { key: 'occupation', label: 'Ocupación / Cargo' },
      { key: 'functions', label: 'Funciones', type: 'textarea' },
      { key: 'employer', label: 'Empleador / Empresa' },
      { key: 'seniority', label: 'Antigüedad en la empresa' },
      { key: 'company_start', label: 'Fecha de Creación de la Empresa', type: 'date' },
      { key: 'employees', label: 'Cantidad de Empleados' },
      { key: 'employee_or_partner', label: '¿Es empleado o socio?', type: 'select' },
      { key: 'business_nature', label: 'Naturaleza del Negocio' },
      { key: 'clients', label: 'Clientes' },
      { key: 'business_address', label: 'Domicilio Comercial' },
      { key: 'website', label: 'Sitio Web' },
      { key: 'other_occupation', label: 'Otra Ocupación Actual (describa)', type: 'textarea' },
    ],
  },
  {
    code: 'SALUD',
    title: 'Salud',
    fields: [
      { key: 'doctor_name', label: 'Nombre del Médico Personal' },
      { key: 'medical_coverage', label: 'Cobertura Médica' },
      { key: 'last_consult', label: 'Fecha Última Consulta Médica', type: 'date' },
      { key: 'consultation_reason', label: 'Motivo de la Consulta', type: 'textarea' },
      { key: 'doctor_contact', label: 'Nombre, Dirección del Médico Consultado' },
      { key: 'studies', label: 'Estudios realizados', type: 'textarea' },
      { key: 'results', label: 'Resultados Obtenidos', type: 'textarea' },
      { key: 'weight', label: 'Peso' },
      {
        key: 'weight_unit',
        label: 'Unidad de peso',
        type: 'select',
        options: [
          { value: 'kg', label: 'kg' },
          { value: 'lbs', label: 'lbs' },
        ],
      },
      { key: 'height', label: 'Altura' },
      {
        key: 'height_unit',
        label: 'Unidad de altura',
        type: 'select',
        options: [
          { value: 'cm', label: 'cm' },
          { value: 'ft', label: 'ft' },
        ],
      },
      { key: 'weight_change', label: 'Cambio de Peso' },
      { key: 'deafness', label: 'Sordera', type: 'yes_no' },
      { key: 'blindness', label: 'Ceguera', type: 'yes_no' },
      { key: 'physical_alterations', label: 'Alteraciones Físicas', type: 'yes_no' },
      { key: 'amputations', label: 'Amputaciones', type: 'yes_no' },
      { key: 'other_impediments', label: 'Otros Impedimentos', type: 'yes_no' },
      { key: 'high_pressure', label: 'Alta Presión', type: 'yes_no' },
      { key: 'diabetes', label: 'Diabetes', type: 'yes_no' },
      { key: 'cancer', label: 'Cáncer', type: 'yes_no' },
      { key: 'cardiac', label: 'Problemas Cardiacos', type: 'yes_no' },
      { key: 'ulcer', label: 'Úlcera', type: 'yes_no' },
      { key: 'surgeries', label: 'Cirugías / Fechas', type: 'textarea' },
      { key: 'important_diseases', label: 'Enfermedades Importantes / Fechas', type: 'textarea' },
      { key: 'prescribed_meds', label: 'Medicamentos con prescripción (Nombre y Dosis)', type: 'textarea' },
      { key: 'non_prescribed_meds', label: 'Medicamentos no recetados (Nombre y Dosis)', type: 'textarea' },
      {
        key: 'salud_detalle_respuesta_afirmativa',
        label: 'Detalle de respuesta afirmativa',
        type: 'textarea',
        visibleWhenAny: visibleWhenAnySi(AFFIRMATIVE_YES_KEYS_SALUD),
      },
    ],
  },
  {
    code: 'RIESGOS_LABORALES',
    title: 'Factores de riesgo en sus labores',
    fields: [
      { key: 'work_risk', label: '¿Está expuesto a algún riesgo por sus labores?', type: 'yes_no' },
      { key: 'work_risk_desc', label: 'Descripción según Ocupación', type: 'textarea' },
      { key: 'safety_rules', label: '¿Hay Normas de Seguridad?', type: 'yes_no' },
      {
        key: 'riesgos_laborales_detalle_respuesta_afirmativa',
        label: 'Detalle de respuesta afirmativa',
        type: 'textarea',
        visibleWhenAny: visibleWhenAnySi(AFFIRMATIVE_YES_KEYS_RIESGOS_LABORALES),
      },
    ],
  },
  {
    code: 'VIAJES',
    title: 'Viajes',
    fields: [
      { key: 'travel_destination', label: 'Destino' },
      { key: 'travel_transport', label: 'Medio' },
      { key: 'travel_reason', label: 'Motivo' },
      { key: 'travel_frequency', label: 'Frecuencia' },
    ],
  },
  {
    code: 'DEPORTES_RIESGO',
    title: 'Deportes de Riesgo',
    fields: [
      { key: 'diving', label: '¿Buceo?', type: 'yes_no' },
      { key: 'racing', label: '¿Carrera de Vehículos?', type: 'yes_no' },
      { key: 'pilot', label: '¿Es Piloto de avión o Piloto Estudiante?', type: 'yes_no' },
      { key: 'ultralight', label: 'Aviones Ultraligeros', type: 'yes_no' },
      { key: 'parachute', label: 'Paracaidismo', type: 'yes_no' },
      { key: 'paragliding', label: 'Parapente', type: 'yes_no' },
      { key: 'climbing', label: 'Escalamiento de montañas', type: 'yes_no' },
      { key: 'other_risk', label: 'Otra Actividad de Riesgo (ampliar)', type: 'textarea' },
      { key: 'accidents', label: '¿Ha tenido accidentes o lesiones practicando deporte?', type: 'yes_no' },
      { key: 'accidents_detail', label: 'Detalle de accidentes o lesiones (deporte)', type: 'textarea' },
      {
        key: 'deportes_riesgo_detalle_respuesta_afirmativa',
        label: 'Detalle de respuesta afirmativa',
        type: 'textarea',
        visibleWhenAny: visibleWhenAnySi(AFFIRMATIVE_YES_KEYS_DEPORTES_RIESGO),
      },
    ],
  },
  {
    code: 'DEPORTES',
    title: 'Deportes',
    fields: [
      { key: 'sports_activity', label: 'Deporte o Actividad Física' },
      { key: 'sports_frequency', label: 'Frecuencia' },
      { key: 'sports_details', label: 'Detalles', type: 'textarea' },
    ],
  },
  {
    code: 'TABACO',
    title: 'Tabaco',
    fields: [
      { key: 'smoker', label: '¿Es Fumador o utiliza algún tipo de tabaco?', type: 'yes_no' },
      { key: 'tobacco_type', label: 'Tipo de Tabaco' },
      { key: 'tobacco_amount', label: 'Cantidad y Frecuencia de Consumo' },
      { key: 'tobacco_period', label: 'Período de Consumo' },
      { key: 'tobacco_last', label: 'Fecha del Último consumo', type: 'date' },
      { key: 'vape', label: '¿Consume cigarrillo electrónico?', type: 'yes_no' },
      { key: 'vape_details', label: 'Cantidad/frecuencia y circunstancias', type: 'textarea' },
    ],
  },
  {
    code: 'ALCOHOL_DROGAS',
    title: 'Alcohol – Drogas',
    fields: [
      { key: 'alcohol', label: '¿Toma Bebidas Alcohólicas?', type: 'yes_no' },
      { key: 'marijuana', label: 'Marihuana', type: 'yes_no' },
      { key: 'amphetamines', label: 'Anfetaminas', type: 'yes_no' },
      { key: 'barbiturics', label: 'Barbitúricos', type: 'yes_no' },
      { key: 'cocaine', label: 'Cocaína', type: 'yes_no' },
      { key: 'lsd', label: 'LSD', type: 'yes_no' },
      { key: 'stimulants', label: 'Estimulantes', type: 'yes_no' },
      { key: 'other_drugs', label: 'Otras Drogas', type: 'yes_no' },
      { key: 'treatment', label: 'Tratamiento por Consumo de Drogas / Alcohol', type: 'yes_no' },
      { key: 'treatment_detail', label: 'Detalle del tratamiento (centro, fechas, etc.)', type: 'textarea' },
      {
        key: 'alcohol_drogas_detalle_respuesta_afirmativa',
        label: 'Detalle de respuesta afirmativa',
        type: 'textarea',
        visibleWhenAny: visibleWhenAnySi(AFFIRMATIVE_YES_KEYS_ALCOHOL_DROGAS),
      },
    ],
  },
  {
    code: 'POLITICA',
    title: 'Política',
    fields: [
      { key: 'pep', label: '¿Es Persona Políticamente Expuesta (PEP)?', type: 'yes_no' },
      { key: 'pep_detail', label: 'Detalle PEP (cargo, organismo, etc.)', type: 'textarea' },
      { key: 'political_party', label: '¿Participa en algún partido político?', type: 'yes_no' },
      { key: 'political_party_detail', label: 'Detalle participación política', type: 'textarea' },
    ],
  },
  {
    code: 'SEGURIDAD',
    title: 'Seguridad',
    fields: [
      { key: 'kidnapping', label: '¿Ha sido Secuestrado o Recibido Amenazas?', type: 'yes_no' },
      { key: 'armored_car', label: 'Auto Blindado', type: 'yes_no' },
      { key: 'weapons', label: 'Portación / Tenencia de Armas', type: 'yes_no' },
      { key: 'weapon_time', label: '¿Hace cuánto tiempo las utiliza?' },
      { key: 'weapon_use', label: '¿En qué circunstancia la porta?' },
      { key: 'weapon_reason', label: 'Razón de portación' },
      { key: 'weapon_type', label: 'Tipo de arma, calibre y modelo' },
      { key: 'weapon_fired', label: '¿Utilizó o disparó el arma en alguna ocasión?', type: 'yes_no' },
      { key: 'weapon_training', label: '¿Ha recibido entrenamiento especial?', type: 'yes_no' },
      { key: 'weapon_training_detail', label: 'Detalle entrenamiento especial (nombre y lugar)', type: 'textarea' },
      { key: 'military', label: '¿Ha pertenecido a alguna fuerza militar o política?', type: 'yes_no' },
      { key: 'military_detail', label: 'Detalle fuerza militar / política', type: 'textarea' },
      { key: 'weapon_maintenance', label: 'Frecuencia de mantenimiento del arma' },
      { key: 'practice_place', label: 'Lugar de práctica' },
      { key: 'security_equipment', label: 'Equipo de seguridad utilizado' },
      { key: 'accidents_security', label: '¿Ha tenido accidentes?', type: 'yes_no' },
      { key: 'personal_guard', label: 'Custodia Personal', type: 'yes_no' },
      {
        key: 'seguridad_detalle_respuesta_afirmativa',
        label: 'Detalle de respuesta afirmativa',
        type: 'textarea',
        visibleWhenAny: visibleWhenAnySi(AFFIRMATIVE_YES_KEYS_SEGURIDAD),
      },
    ],
  },
  {
    code: 'HISTORIA_SEGUROS',
    title: 'Historia de Seguros',
    fields: [
      { key: 'insurance_date', label: 'Fecha del seguro', type: 'date' },
      { key: 'insurance_company', label: 'Compañía' },
      { key: 'insurance_amount', label: 'Monto' },
      { key: 'insurance_reason', label: 'Motivo del seguro', type: 'textarea' },
      { key: 'simultaneous_policy', label: 'Seguro de vida en otra compañía (detallar)', type: 'textarea' },
    ],
  },
  {
    code: 'DETALLE_SEGURO',
    title: 'Detalle del seguro',
    fields: [
      { key: 'insurance_object', label: 'Objeto del seguro' },
      { key: 'policy_holder', label: 'Tomador de la Póliza' },
      { key: 'policy_payer', label: 'Pagador de la Póliza' },
      { key: 'bank_name', label: 'Banco de origen de fondos' },
      { key: 'funds_origin', label: 'Origen de fondos', type: 'textarea' },
      { key: 'previous_rejected', label: '¿Le han Rechazado alguna Solicitud anteriormente?', type: 'yes_no' },
      {
        key: 'previous_rejection_reason',
        label: 'Motivo del Rechazo',
        type: 'textarea',
        visibleWhen: { key: 'previous_rejected', values: ['Sí'] },
      },
      { key: 'replaces_policy', label: '¿Este Seguro Reemplaza una Póliza Actual?', type: 'yes_no' },
    ],
  },
  {
    code: 'INGRESOS',
    title: 'Ingresos',
    fields: [
      { key: 'earned_income', label: 'Ingreso Ganado Anual' },
      { key: 'earned_concept', label: 'Concepto (Sueldo, Comisiones, etc.)', type: 'textarea' },
      { key: 'unearned_income', label: 'Ingresos Anuales No Ganados' },
      { key: 'unearned_concept', label: 'Concepto (Dividendos, etc.)', type: 'textarea' },
      { key: 'total_income', label: 'Ingreso Total Anual' },
    ],
  },
  {
    code: 'ACTIVO_PERSONAL',
    title: 'Activo Personal',
    fields: [
      { key: 'total_assets', label: 'Total Activo Personal' },
      { key: 'real_estate', label: 'Inmuebles / Bienes Raíces' },
      { key: 'cash_bank', label: 'Efectivo en banco' },
      { key: 'goods', label: 'Bienes (vehículos, arte, etc.)', type: 'textarea' },
      { key: 'society', label: 'Participación en Sociedades' },
      { key: 'stocks', label: 'Acciones y Bonos' },
      { key: 'other_assets', label: 'Otros Activos (Detalles)', type: 'textarea' },
      { key: 'receivables', label: 'Cuentas por Cobrar' },
    ],
  },
  {
    code: 'PASIVO_PERSONAL',
    title: 'Pasivo Personal',
    fields: [{ key: 'total_liabilities', label: 'Total Pasivo Personal' }],
  },
  {
    code: 'FINANZAS_OTROS',
    title: 'Finanzas – Otros',
    fields: [
      { key: 'banks', label: 'Bancos con los cuales opera' },
      { key: 'bank_relationship', label: 'Antigüedad' },
      { key: 'credit_cards', label: 'Tarjetas de crédito' },
      { key: 'bankruptcy', label: '¿Está en Quiebra Comercial?', type: 'yes_no' },
      { key: 'negative_history', label: 'Antecedentes comerciales negativos', type: 'textarea' },
    ],
  },
  {
    code: 'HISTORIAL_MANEJO',
    title: 'Historial de Manejo',
    fields: [
      { key: 'dui', label: 'Condenas por DUI en últimos 5 años', type: 'textarea' },
      { key: 'traffic', label: 'Infracciones de tránsito últimos 3 años', type: 'textarea' },
    ],
  },
  {
    code: 'JUICIOS',
    title: 'Juicios',
    fields: [
      { key: 'criminal_case', label: 'Juicio Penal', type: 'yes_no' },
      { key: 'civil_case', label: 'Juicio Civil', type: 'yes_no' },
      { key: 'commercial_case', label: 'Juicio Comercial', type: 'yes_no' },
      { key: 'labor_case', label: 'Juicio Laboral', type: 'yes_no' },
      {
        key: 'juicios_detalle_respuesta_afirmativa',
        label: 'Detalle de respuesta afirmativa',
        type: 'textarea',
        visibleWhenAny: visibleWhenAnySi(AFFIRMATIVE_YES_KEYS_JUICIOS),
      },
      { key: 'arrested', label: '¿Ha sido Arrestado? Detallar', type: 'textarea' },
    ],
  },
  {
    code: 'COMENTARIOS',
    title: 'Ampliación o Comentarios Adicional',
    fields: [{ key: 'additional_comments', label: 'Comentarios', type: 'textarea' }],
  },
];
